microsoft/cpp_client_telemetry

lib/jni/LogManager_jni.cpp
lib/offline/OfflineStorage_Room.cpp
tests/unittests/OfflineStorageTests_Room.cpp

Attempt to mitigate crashes during upload on Android.
We are seeing crashes in production on Android, with GetAndReserveRecords in the call stacks. Let's attempt to prevent the crashes via try/catch, and log the errors.

Mitigation for OfflineRoom crashes

---

lib/include/public/Version.hpp

Release v3.5.25 to include the recent Obj-C warnings fix.

Release v3.5.25

---

lib/pal/universal/WindowsRuntimeDeviceInformationImpl.cpp
lib/pal/universal/WindowsRuntimeNetworkInformationImpl.cpp

`NetworkInformation::GetInternetConnectionProfile()` API may fail under some unknown scenarios on some Windows versions, as well as it may cause NLM COM object initialization delay of up to 3-6 seconds. For those applications that need instantaneous initialization - we start respecting the existing `configuration[CFG_BOOL_ENABLE_NET_DETECT]` flag, to turn the network detection logic off entirely.
Usage example that shows how to turn the network detection off:
```cpp
auto& config = LogManager::GetLogConfiguration();
config[CFG_BOOL_ENABLE_NET_DETECT] = false;
...
ILogger *logger = LogManager::Initialize();
```
Since the feature flag already existed for Win32 Desktop applications, we merely extend the same logic to apply to UWP/WinRT apps as well. Subsequent PR may try to implement a …

Allow to turn Network Detector off for WinRT/UWP

---

lib/include/public/IDataInspector.hpp

Update Submodule commit point to reflect module updates.
Also doing a quick cleanup in `IDataInspector`.

Update Submodule commit

---

lib/include/public/Version.hpp

Just an update to Versions.hpp.

Prepare for release 3.5.63

---

wrappers/obj-c/ODWLogConfiguration.mm

Prospective fix for crash when calling `ODWLogConfiguration.set`

Prospective fix for crash

---

tests/unittests/obj-c/ODWLogConfigurationTests.mm
wrappers/obj-c/ODWLogConfiguration.h
wrappers/obj-c/ODWLogConfiguration.mm

Add a function to the log configuration to set the host

[ObjC] Add function to set host

---

lib/include/public/Version.hpp

Prepare for release 3.5.89

---

lib/CMakeLists.txt

Update commit ID for modules.
Also fix Macro redefinition that is breaking gcc.

Update Modules commit

---

lib/include/public/Version.hpp

This PR is to generate  a new release of SDK to include a fix in this PR:
https://github.com/microsoft/cpp_client_telemetry/pull/847

Updated version to 3.5.127.1

---

Solutions/Clienttelemetry/Clienttelemetry.vcxitems.filters
Solutions/MSTelemetrySDK.sln
tests/functests/CMakeLists.txt
tests/functests/FuncTests.vcxproj

1. Update of the Modules commit with updated tests.
2. Update of the test infra to consume defaultdataviewer functional tests.
a. tests/functests/CMakeLists.txt
b. tests/functests/FuncTests.vcxproj
3. Update of a couple of VS files that are continuously being updated by VS.
a. Solutions/Clienttelemetry/Clienttelemetry.vcxitems.filters
b. ~Solutions/MSTelemetrySDK.sln~

Module, Tests, and VS Solution files updates

---

.github/CODEOWNERS

Let's give the magic powers to Sid. @sid-dahiya 
He's been a long-time here, practically "old-timer" - surprising that he's not on this list.
I hope there are no objections from Sid and others? 😃

Update CODEOWNERS: add Sid.

---

tests/unittests/CMakeLists.txt
tests/unittests/EventPropertiesDecoratorTests.cpp
tests/unittests/UnitTests.vcxproj
tests/unittests/UnitTests.vcxproj.filters
tests/unittests/unittests-ios.xcodeproj/project.pbxproj

Adding UT coverage for 'decorate' and 'dropPiiPartA' behavior

Adding unit tests for EventPropertiesDecorator

---

tests/common/iOSWrapper.mm

XCTIssue is latest supported Apple XCode 12 API for recording issues

Use xcode12 test issue recording API rather than deprecated one

---

.github/ISSUE_TEMPLATE/question.md
README.md

Fix and update links

---

CMakeLists.txt

fixing CFLAGS for AppleClang

---

lib/include/public/Version.hpp

Update version to 3.5.270 to prep for new release.

Update version to 3.5.270

---

lib/pal/PAL.cpp

Fix the build break for Ubuntu 16 LTS #949

---

lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/PrivacyGuard.java
lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/PrivacyGuardInitConfig.java
lib/jni/PrivacyGuard_jni.cpp
wrappers/obj-c/ODWPrivacyGuard.mm
wrappers/obj-c/ODWPrivacyGuardInitConfig.h

This change is bringing in the latest commit from the Modules repo.
With the modules change, the relevant Obj-C and Java wrappers have also been updated.

Update modules commit and related wrappers

---

lib/include/public/Version.hpp

Updating version file to prep for release.

Update version to 3.5.321.1

---

lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/HttpClient.java
lib/android_build/maesdk/src/test/java/com/microsoft/applications/events/EventsUnitTest.java
lib/pal/posix/SystemInformationImpl_Android.cpp

* add device class for Android
* Fix CI build fail and add test for device_class
* Fix test build fail
* Resolve comments
Co-authored-by: Wangyang Dai <wadai@microsoft.com>
Co-authored-by: Lalit Kumar Bhasin <lalit_fin@yahoo.com>

Add device class field for Android (#951)

---

lib/include/public/mat.h

Add explicit tagnames so types can be forward declared

---

lib/include/public/Version.hpp

Updates modules to the latest commit

Update Modules to latest commit

---

.gitmodules
lib/include/public/CommonFields.h

Add support for UTC Privacy Product and Privacy Data category.
A subsequent change in modules will consume these definitions.

Add support for utc new privacy fields 

---

lib/include/public/Version.hpp

1. Update the submodule pointer to grab the PG changes.
https://github.com/microsoft/cpp_client_telemetry_modules/commit/1f0cccb443b092003a7ec46d4954a634c60eea4b
2. Bump version for new release.

Update modules version and bump version for new release

---

lib/include/public/Version.hpp

Bumping up the version to create a new release on github.

Updating version number to 3.8.32.1 to create a new release

---

tests/unittests/UnitTests.vcxproj

PrivacyGuard submodule has been updated and merged with the systematic sampling feature. This change updates the modules to the latest commit and adds a unit test to the project file.

Update submodule to latest commit for PrivacyGuard

---

lib/pal/posix/DeviceInformationImpl.cpp

We have been noticing some device makes have pii emails in them (for some unknown reason). We should remove just to be safe

Add scrubbing to Device Make if it contains @ character

---

.github/workflows/build-android.yml
lib/android_build/maesdk/build.gradle

Make unit test compatible with Java 17

Upgrade mockito test dependency to be compatible with new Java version

---

lib/utils/Utils.cpp

Fixes microsoft/cpp_client_telemetry#1316

Use GetTempPath2W whenever available

---

lib/include/public/Version.hpp

bumping version to 3.9.163.1

---

lib/include/public/Version.hpp

updating version to 3.9.205

---

CMakeLists.txt

Follow up for https://github.com/microsoft/cpp_client_telemetry/pull/1326#discussion_r1949560912

Delete unreachable code in CMakeLists.txt

---

lib/include/public/Version.hpp

update commit for lib to reattach to master
updated version

reattach lib/modules to master
