tests/common/MockIEcsClient.hpp, tests/common/MockIHttpClient.hpp, tests/common/MockILogManagerInternal.hpp, tests/common/MockIOfflineStorage.hpp, tests/common/MockIOfflineStorageObserver.hpp, tests/common/MockIRuntimeConfig.hpp, tests/common/MockISemanticContext.hpp, tests/common/MockISqlite3Proxy.hpp, tests/common/MockITelemetrySystem.hpp, tests/common/MockITenantDataSerializer.hpp, tests/unittests/UnitTests.vcxproj, tests/unittests/UnitTests.vcxproj.filters
`MOCK_METHOD` macros and their ilk appear to not append the `override` keyword to their generated method declarations. As such I'm disabling Clang's[ inconsistent-missing-override](https://clang.llvm.org/docs/DiagnosticsReference.html#winconsistent-missing-override) warning around only those types.
I also cleaned up the vcproj, let me know if I missed anything and I'm happy to undo that.
=> Suppress Clang inconsistent-missing-override warnings around GMock Macros

.github/workflows/build-android.yml, .github/workflows/build-ios-latest.yml, .github/workflows/build-posix-latest.yml, .github/workflows/build-windows-clang.yaml, .github/workflows/build-windows-vs2017.yaml, .github/workflows/build-windows-vs2019.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/spellcheck.yml, .github/workflows/test-android-mac.yml, .github/workflows/test-win-latest.yml, README.md, lib/android_build/app/src/androidTest/java/com/microsoft/applications/events/maesdktest/LogManagerDDVUnitTest.java, lib/include/mat/config-default.h, lib/offline/OfflineStorageFactory.cpp, lib/offline/OfflineStorageFactory.hpp
Motivation for this PR:
- make sure that the entire set of tests for all platforms is functional and passing even if compiling without private modules.
- remove private submodules cloning from GitHub Actions. Azure DevOps / VSO workflow may still be able to clone all if build account is explicitly authorized (for local runs in your own Docker). But we are not longer using PAT token for the clone action here.
While testing these changes I also did a full build in Visual Studio to cover additional extra projects that are not presently covered by CI, e.g. `ClientTelemetry3s.lib` - super-slim static build. It turned out that this slim build got broken some time ago due to Offline Storage factory refactor in `OfflineStorageFactory.cpp`. I fixed it too. We need to add slim build to CI later on, …
=> Build is broken if compiling without modules

wrappers/obj-c/ODWLogManager.mm
Description:
While updating the pod spec with version 3.5.19, the local build verification failed with below error:
`- ERROR | [iOS] xcodebuild:  OneDsCppSdk.iOS/wrappers/obj-c/ODWLogManager.mm:207:1: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]`
When I looked at recent changes I found [a recent change](https://github.com/microsoft/cpp_client_telemetry/pull/750/files#diff-e120c7a402598bfdf01df679f15c6d3d87dc63c9a59354d7fd0a2ec188040b94R197) in which we do not return an instance of ODWStatus in these two methods in `ODWLogManager.mm`
```
+(ODWStatus)flush
+(ODWStatus)flushAndTeardown 
```
Solution: 
1. Return ODWEfail when exception occurs in these two methods.
2. Return ODWStatus in value returned from `LogManager::FlushAndTeardown()` in …
=> Adding return value statements  in flush and flushAndTearDown methods of ODWLogManager.mm

wrappers/obj-c/ODWDiagnosticDataViewer.h, wrappers/obj-c/ODWLogConfiguration.h
Fixed documentation warnings in  ObjC layer which cause XCode build to fail when "Documentation Comments" build setting is "YES" for a build target.
=> Fixed documentation warnings in  ObjC layer which cause XCode build to fail

lib/http/HttpClient_Apple.mm, lib/http/HttpClient_WinRt.cpp, lib/jni/Utils_jni.cpp, lib/utils/Utils.hpp, tests/unittests/PackagerTests.cpp, tests/unittests/StringUtilsTests.cpp, tests/unittests/UtilsTests.cpp
- Fixed a couple remaining build breaks that I missed in https://github.com/microsoft/cpp_client_telemetry/pull/772.
- Moved the applicable Unit Test to StringUtilsTests.cpp
- Updated the Modules rev.
=> Final Steps of Moving String methods to StringUtils.hpp

CMakeLists.txt, build-ios.sh
Add support for 1DSSDK iOS build script to generate binary for iOS arm simulator.
Context:
As part of Apple Silicon release, latest XCode version allows to debug apps on iOS arm64 simulators (previously only x86_64 simulators were available). This change allows build-ios.sh build script to generate 1DS SDK static library than can be used to link into products targeting iOS arm simulator.
=> Add support for 1DSSDK iOS build script to generate binary for iOS arm simulator

lib/utils/StringConversion.cpp, lib/utils/StringConversion.hpp, tests/unittests/StringUtilsTests.cpp
codecvt_utf8_utf16 has been deprecated in c++17, and it has behaved inconsistently on different standard libraries, like libc++. Since these conversions are only used on Windows, this switches to the windows.h utility.
Related to #191 and #262
=> Remove main usage of codecvt_utf8_utf16

lib/jni/LogManager_jni.cpp, wrappers/obj-c/ODWLogConfiguration.h, wrappers/obj-c/ODWLogConfiguration.mm, wrappers/obj-c/ODWLogConfiguration_private.h, wrappers/obj-c/ODWLogManager.h, wrappers/obj-c/ODWLogManager.mm
Currently iOS only uses default config, which makes side-by-side loggers with different configuration not possible. close #784
=> Expose LogConfiguration.getLogConfigurationCopy() and LogManager.loggerWithTenant() with custom config on iOS

lib/http/HttpClient_Android.cpp, lib/http/HttpClient_Android.hpp, lib/offline/OfflineStorageFactory.cpp, lib/offline/OfflineStorage_Room.cpp
We are seeing OOM crashes on the oldest and smallest (DRAM) devices.
If we OOM in the database or upload code, we should simply do nothing. We
may succeed on a subsequent attempt, but in any event we do not want to
crash the application because telemetry failed to upload.
=> Mitigate OOM errors on Android

lib/include/public/Version.hpp, lib/include/public/Version.hpp.template
Two changes:
- `Version.hpp` has been refactored recently, but the `Version.hpp.template` file that re-generates the `Version.hpp` has not been adjusted accordingly. I'm fixing it now.
- updated `Version.hpp` with today's build date to create a release tag off that
=> Prepare for release 3.5.57

lib/shared/LogConfigurationCX.cpp, lib/shared/LogConfigurationCX.hpp
**Issue:** Cache file size limit is not customizable in the C# projection
**Fix:** Expose public properties that would let users customize the cache file size limit. Also expose a bool that would allow users to enable flush the cache file once limit is reached.
=> Expose file cache size limit and db drop property in C# projection

lib/api/LogManagerImpl.cpp, lib/api/LogManagerImpl.hpp, lib/include/public/IDataInspector.hpp, lib/include/public/ILogManager.hpp, lib/include/public/NullObjects.hpp
the follow up changes will need to be to either the `IDataInspector` to have a public function that identifies the type of DataInspector is it (such as `UniqueIdentifier()` which will always describe the type of identifier) or we could change the ILogManager interface to include identifiers when adding new IDataInspectors (such as change `SetDataInspector(std::shared_ptr<IDataInspector>)` to `AddDataInspector(std::string, std::shared_ptr<IDataInspector>)`) or we could use a call to `typeid(currentInspector).name()` and compare that to the currently present `IDataInspector`'s however I'm not confident that using `typeid` wouldn't cause any issues down the road. This last solution I believe would reduce the number public interface changes
=> Add Support for Mulitple IDataInspectors within Log Manager

lib/include/public/Version.hpp, lib/include/public/Version.hpp.template
Also update the generated file, since in my previous PR I presumed that was done automatically overnight. Mistake on my end, yuck.
=> Re-remove the namespace macros from Version.hpp.template

tests/functests/EventDecoderListener.cpp
Full warning-as-error text:
```
d:\office\dev\telemetry\ariasdk\next\tests\functests\EventDecoderListener.cpp(64,79) : error: format specifies type 'unsigned long long' but the argument has type 'uint64_t' (aka 'unsigned long') [-Werror,-Wformat]
printf("%20s: seq=%llu, ts=%llu, type=0x%08x, p1=%zu, p2=%zu\n", lbl, e.seq, e.ts, e.type, e.param1, e.param2);
~~~~                                                ^~~~~
%lu
d:\office\dev\telemetry\ariasdk\next\tests\functests\EventDecoderListener.cpp(64,86) : error: format specifies type 'unsigned long long' but the argument has type 'uint64_t' (aka 'unsigned long') [-Werror,-Wformat]
printf("%20s: seq=%llu, ts=%llu, type=0x%08x, p1=%zu, p2=%zu\n", lbl, e.seq, e.ts, e.type, e.param1, e.param2);
~~~~ …
```
=> Fix Clang -Wformat warning on 64 bit Droid

lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/HttpClient.java
Calls into ConnectivityManager can sometimes throw exceptions, which causes crashes on HttpClient initialization. According to some posts online, some of these exceptions, such as a SecurityException due to package permissions (might also be relevant to Android Work Profile management), and RuntimeExceptions when too many callbacks are registered, are currently not handled in the Logger code. 
Capturing these calls in a try/catch loop ensures that we can still continue with the proper logger initialization, even if we don't have full insights into the changes in the network state of the device.
Similar issue is reported here: https://github.com/DataDog/dd-sdk-android/issues/413
=> Capturing ConnectivityManager exceptions in Android

wrappers/obj-c/ODWLogManager.mm
Right now we only set the initialized property when the `init` function is called. This property should be set in the inner function which is called from other functions as well.
=> Move setting initialized to inner function

lib/include/mat/config-default.h
We fixed PrivacyGuard build issues with gcc a while back, but the config wasn't updated then. Fixing it now.
=> Build Privacy Guard for GCC

lib/config/RuntimeConfig_Default.hpp, lib/offline/SQLiteWrapper.hpp
Original customer issue reported by email.
There are three CodeQL 'errors' observed with **certain custom ruleset**. None of these issues get reported by our default ruleset on GitHub CodeQL run. And none of them, in essence, are security issues - since on all codepaths the issues described here are "impossible to happen". But I'm fixing these nevertheless to eliminate the 'noise' in the customer's build pipeline.
CodeQL issues are:
| Severity	| Code	| Description	| Project	| File	| Line	| Suppression | State	| Priority |
|---------|---------|---------------|---------|----|---------|--------------|----------|--------|
| Error	| SM02311	|  In GetCollectorUrl result of `[call](1)` to `[operator const char *](2)` is dereferenced here and may be null.	| 	| …
=> Fix CodeQL warnings

lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/DebugEvent.java, lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/LogManagerProvider.java
Some applications are seeing a Java exception that the field `long nativeLogManager` is not present in the java class LogManagerImpl. Possibly R8 has minified the field out of existence; at any rate, the @Keep annotation should not hurt and might help.
=> Annotate JNI-accessed class and fields

tests/unittests/obj-c/ODWLogConfigurationTests.mm, wrappers/obj-c/ODWLogConfiguration.h, wrappers/obj-c/ODWLogConfiguration.mm
The `ODWLogConfiguration.set` function is not behaving as expected. Update the function and add a unit test
=> Fix ODWLogConfiguration.set function

lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/LogManagerProvider.java, lib/jni/LogManager_jni.cpp
Add error checking in the getLogger method. Some applications are
seeing Java exceptions (no such field) from the nativeGetLogger method.
=> Error checking for introspection failures

wrappers/obj-c/ODWLogger.mm
Issue:
Our project was sending bools to kusto as longs instead of true, false. We are using the objective-c wrapper of the sdk. I believe there is an issue in the the sdk to check if an objective-c object is actually a bool
```
strcmp([num objCType], @encode(BOOL))==0 
```
However I found several posts saying this will not work for 64-bit systems (most iphones/simulators today) because an Obj-C Bool is actually an unsigned char.
https://stackoverflow.com/questions/23425187/nsnumber-with-bool-is-no-bool-on-64bit/23426415
Solution:
This post seemed to have an acceptable fix
https://github.com/gabriel/MPMessagePack/commit/c8aeebf820c92a7cd9dbd0fabfa758cca34488a8
=> Fix bool check for Objective-C

tests/functests/FuncTests.vcxproj, tests/unittests/UnitTests.vcxproj
This yields better build perf as these projects only build the test files they need, rather than compiling the entirety of files contained within ClientTelemetry.lib. 
The tests will, of course, still depend on ClientTelemetry.lib, and any changes in constituent files will require a re-lib and re-link, but it means that we'll be compiling each file N-2 times, which is probably a win :)
On the build perf improvement: Looking at a couple PRs, the Test-Win32 Release loop looks like it's saving 6-7 minutes out of ~20 minutes (or roughly 35%). Not yet at the non-windows loop speeds, but makes my calculator show a smiley face.
=> Stop Unit and Func tests from recompiling all of the files that constitute clienttelemetry.lib

.github/workflows/spellcheck.yml, lib/api/LogConfiguration.cpp, lib/include/mat/json.hpp
Fixes #833
Integrate the latest Released version of json.hpp from https://github.com/nlohmann/json/releases/tag/v3.9.1
Presently following the existing process, i.e. drop-in a copy of it.
We may later on consider mapping it as submodule under `third_party`. But not in this PR.
cc: @SahilAshar
=> Update json.hpp to v3.9.1

lib/api/ContextFieldsProvider.cpp, lib/pal/desktop/WindowsDesktopSystemInformationImpl.cpp
Cherry-picking from release branch to prevent us from having to cherry-pick explicitly to multiple releases.
=> Add support for custom r: device IDs

lib/pal/desktop/WindowsDesktopSystemInformationImpl.cpp
Cherry-picking from release branch to prevent us from having to cherry-pick explicitly to multiple releases.
=> Workaround for undefined RRF_SUBKEY_WOW6464KEY regkey

lib/include/public/Version.hpp, lib/include/public/Version.hpp.template
Cherry-picking from release branch to prevent us from having to cherry-pick explicitly to multiple releases.
=> Fix error: ctmacros.hpp file not found with <angled> include

Solutions/win32-dll/win32-dll.vcxproj
The win32-dll project doesn't need to rebuild all the .cpp files in ClientTelemetry.vcxitems (et al), rather it should consume what's produced by win32-lib.
This also should help improve MSBuild build speed (and loop times) as each .cpp file will need to be built one fewer time.
=> win32-dll.vcxproj should consume products of win32-lib.vcxproj, not rebuild all CPP files therein.

lib/pal/posix/sysinfo_sources.cpp
ext_os_name string on openSUSE may contain quotes for example,
"opensuse-leap"
"opensuse-tumbleweed"
We would like to remove these quotes.
=> ID in /etc/os-release on openSUSE contains quotes

lib/include/mat/config-MIP.h, lib/include/mat/config-MSIPC.h, lib/include/mat/config-compact-dll.h, lib/include/mat/config-compact-exp.h, lib/include/mat/config-compact-min.h, lib/include/mat/config-compact-noutc.h, lib/include/mat/config-compact.h, lib/include/mat/config-default-cs4.h, lib/include/mat/config-default.h, lib/include/mat/config-net40.h, lib/include/mat/config-versionPrefix.h
In one of the other PRs I noticed that we _somehow_ end up defining the same feature macros twice.
As a good gesture, appending `#pragma once` where it was missing. The actual `config.h` has the include guards around it, and the expectation has generally been that all other minor feature customization configs get included only from that main file via `#include CONFIG_CUSTOM_H`. So this include rule is violated somewhere around unit tests for custom features. Adding `#pragma once` seems like a good thing to do.
Unrelated to `pragma` - I noticed that recent features were added to `config-default.h` for Common Schema 3 build. But not to `config-default-cs4.h` for Common Schema 4 build, which we were planning to embrace some time this year as the default. I'm adding these new feature flags to …
=> Ensure config headers are included once

lib/decoder/PayloadDecoder.cpp
Add mat/config.h include to ensure that we have access to CONFIG_CUSTOM_H for clients to use customized defines, such as Edge.
=> Add mat/config.h include to PayloadDecoder.cpp as it is causing undesired behavior in MS Edge.

wrappers/obj-c/ODWLogManager.mm
**Background**:
There is a race between last logging and OneDS engine shutdown.
The odds are stacked against us in that race in Teams iOS code. As the last item in -[TeamSpaceApp applicationWillTerminate:] in our code we are logging:
`LogInfoAH(logger, @"appWillTerminate");`
Then we give the control back to the OS, which sends the notification about the same to all registered listeners, including our TSOneDSTelemetryLogManager. The logged info is being dispatched in the background at the same time. So we spend some time before we reach that place where we set `canUseSDK=false`. To speed up the process:
1. do not log that info in the last moment
2. do not rely on iOS NotificationCanter to deliver the applicationWillTerminate message
3. speed up to set the flag by calling the …
=> [Obj-Wrapper] Set canUseSDk flag to false before pause transmission

lib/pal/PAL.cpp
When compiling on MSVC, `PAL.cpp` throws this warning (which is treated as an error).
```
warning C4828: The file contains a character starting at offset 0x321a that is illegal in the current source character set (codepage 65001)
```
Changing from the "curly quote" ( ` ‘T’ ` ) to a standard one ( ` 'T' ` ) fixes this issue.
=> Illegal Character Causing Build Errors in MSVC

CMakeLists.txt, Solutions/net40/net40.vcxproj, Solutions/win10-cs/win10-cs.vcxproj, Solutions/win10-dll/win10-dll.vcxproj, Solutions/win10-lib/win10-lib.vcxproj, Solutions/win32-dll/win32-dll.vcxproj, Solutions/win32-lib/win32-lib.vcxproj, lib/api/CorrelationVector.cpp, lib/decoder/PayloadDecoder.cpp, lib/tracing/api/DebugLogger.hpp
Windows.h, for a number of probably good reasons at the time, `#define`s `min` and `max`. These of course conflict with std::min and std::max methods.
Windows also offers NOMINMAX, which avoids those defines. 
If there are situations where the Windows SDK min and max macros are necessary (currently none, but there might be some in the future) we should `#undef NOMINMAX` in those specific .cpp files:
```C++
#pragma push_macro("NOMINMAX")
#undef NOMINMAX
#include <windows.h> // or whatever windows header
... // use the icky macros of badness.
#pragma pop_macro("NOMINMAX")```
=> Set the NOMINMAX Macro in the Build

Solutions/win10-cs/win10-cs.vcxproj, Solutions/win10-lib/win10-lib.vcxproj, examples/c/SampleC/SampleC.vcxproj, examples/cpp/SampleCppUWP/SampleCppUWP.vcxproj
In short, the essence of this fix:
1. Try to autodetect the latest Windows 10 SDK.
2. Try to autodetect the Visual Studio version:
- if Visual Studio 2019 is detected, then use `v142` tooling for the samples.
- if Visual Studio 2017 is detected, then use `v141` tooling for the samples.
This ensures that if we "Build All..." in Visual Studio 2019 IDE, even without v141 (vs2017) tools installed, all projects including samples are built successfully.
=> Fix Visual Studio 2019 build issues in samples

lib/stats/MetaStats.cpp
This issue appears to be unique to clang-11 on Linux. Compiler triggers warning about unused variable. That warning on latest is now treated as error. Removing the unused mutex to fix the error.
=> Remove unused mutex that triggers clang-11 compiler warning (and error)

lib/include/mat/config-default-exp.h
New build config. Follow [this process](https://github.com/microsoft/cpp_client_telemetry/blob/master/docs/building-custom-SKU.md) to build with EXP. Use `CONFIG_CUSTOM_H=config-default-exp.h`.
@anaaru - alternatively you may also use this to diff against the standard `config-default.h` and just patch it as part of vcpkg process. The only change is removing gated check around `HAVE_MAT_EXP` and `HAVE_MAT_FIFOSTORAGE`.
Third option is to pass `HAVE_PRIVATE_MODULES`, I think you already handled that.
=> Add configuration example that includes A/B EXP feature

CMakeLists.txt
CMakeLists requires some adjustments to build properly for Windows and MSVC.
- Set proper build flags
- Adjust Debug vs non-Debug flags to allow for "RelWithDebInfo" and other release types
=> Adjust CMakeLists.txt to build for Windows with MSVC

Solutions/win32-lib/win32-lib.vcxproj
This PR addresses: #888 
The 'win32-lib.vcxproj' builds a static lib, but the project file defines `MATSDK_SHARED_LIB`, which causes `__declspec(dllexport)` to be applied to members. Any DLL consuming the static lib will end-up exporting the `__declspec(dllexport)`-annotated methods - ~245 of them.
My team have had a patch for this fix for a while - I apologize, I hadn't realize an issue hadn't been filed. This doesn't fix the CMake build - which appears to define `MATSDK_SHARED_LIB` too broadly - but I'm not sure if the Windows CMake build is supported.
=> 'win32-lib.vcxproj' shouldn't define MATSDK_SHARED_LIB

.github/workflows/build-android.yml, .github/workflows/build-ios-latest.yml, .github/workflows/build-posix-latest.yml, .github/workflows/build-windows-clang.yaml.off, .github/workflows/build-windows-vs2017.yaml.off, .github/workflows/build-windows-vs2019.yaml, .github/workflows/test-android-mac.yml, .github/workflows/test-win-latest.yml
Add `dev` branch to CI and Pull Request process. This would guarantee that any changes we implement in `v4` are stable and mergeable back into `master` ( `main` ) as a full-promote, whenever we are ready for that.
=> Add CI for dev branch

wrappers/obj-c/ODWPrivacyGuard.h, wrappers/obj-c/ODWPrivacyGuard.mm, wrappers/obj-c/main.mm
Also make re-initialization of Privacy Guard a no-op.
=> Add Reset Privacy Guard API

lib/decorators/EventPropertiesDecorator.hpp
EventPropertiesDecorator ignores any value specified in EventProperties::SetTimestamp and all records get the timestamp value set in BaseDecorator (PAL::getUtcSystemTimeinTicks()).  This change updates EventPropertiesDecorator::decorate to set record.time to eventProperties.GetTimestamp() if it is non-zero.
=> Update EventPropertiesDecorator to respect the value set by SetTimestamp

lib/pal/typename.hpp
The `TYPENAME` method should honor the `no-rtti` build flag when using GCC building, just like win32 does.
=> honor no-rtti setting

lib/api/LogManagerImpl.cpp, lib/include/public/ILogConfiguration.hpp
We want to add the ability to disable deferred cleanup of the loggers, so that XAL's cleanup properly cleans up, and our clients can test for memory leaks correctly. 
Happy to change flag name if it's not inline with your style guide.
@lubeltra for vis
=> Adding Config Option to Disable Zombie Logger Logic

Solutions/win32-lib/win32-lib.vcxproj, Solutions/win32-mini-lib/win32-mini-lib.vcxproj, googletest/googlemock/msvc/2015/gmock.vcxproj, googletest/googletest/msvc/gtest.vcxproj, sqlite/sqlite.vcxproj, tests/functests/FuncTests.vcxproj, tests/unittests/UnitTests.vcxproj, zlib/contrib/vstudio/vc14/zlibvc.vcxproj
=> enable MultiProcessorCompilation `/MP` to speed up compilation

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/build-android.yml, .github/workflows/build-ios-latest.yml, .github/workflows/build-posix-latest.yml, .github/workflows/build-windows-clang.yaml.off, .github/workflows/build-windows-vs2017.yaml.off, .github/workflows/build-windows-vs2019.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/spellcheck.yml, .github/workflows/test-android-mac.yml.off, .github/workflows/test-win-latest.yml
As discussed in #924, this is the first step for migration to main - adding `main` branch to the list of branches used to trigger actions in github actions.
=> Prep step for migration from master to main

README.md, docs/Coding style.md, docs/List-of-OSS-Components.md, docs/cpp-start-android.md, docs/cpp-start-ios.md, docs/cpp-start-linux.md, docs/cpp-start-windows.md, docs/dev-branch-process.md, docs/start_macOS_iOS.md, docs/versioning.md, tools/ports/mstelemetry/portfile.cmake
In continuation with process of migration to main branch (#924), the `master` branch has bee renamed to `main` through Github UI, a new `master` branch has been created from this renamed branch and locked ( kind-of ) for any new commits. 
This PR fixes all the references to `master` branch in this repo along with updating the current release version, and release plan.
=> Migrate from master to main : fix master branch references

docs/use-after-free.md, lib/android_build/app/src/androidTest/java/com/microsoft/applications/events/maesdktest/SDKUnitNativeTest.java, lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/ILogManager.java, lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/LogManager.java, lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/LogManagerProvider.java, lib/api/LogManagerImpl.cpp, lib/api/LogManagerImpl.hpp, lib/api/Logger.cpp, lib/include/public/ILogManager.hpp, lib/include/public/LogManagerBase.hpp, lib/include/public/NullObjects.hpp, lib/jni/LogManager_jni.cpp, lib/offline/OfflineStorageHandler.cpp, lib/tpm/TransmissionPolicyManager.cpp, tests/functests/BasicFuncTests.cpp, tests/unittests/LogManagerImplTests.cpp
Adds methods to ILogManager to support pause and resume. During pause, loggers do not log, flush does not flush, and tpm does not start uploads.
This allows client software to quiesce these activities, either for an operating-system "you are in the background" state change (iOS wants background apps to negotiate for time to do activities like persisting to the database) or a "you are about to tear down all objects" (iOS, again).
Happily, Android kills applications with SIGKILL and there is no such thing as a bad application exit, but even on that platform one might want to sleep-hard or know when the SDK is idle and paused.
No iOS ObjC wrapper in this PR because I do not have a Mac and therefore no xcode.'
This PR includes the Java wrapper changes and Java tests for the interface, and C++ …
=> Pause and resume-or-terminate

wrappers/obj-c/ODWLogManager.mm
languageCode and contryCode are not supported for Mac 10.11 or earlier versions as per Apple documentation: https://developer.apple.com/documentation/foundation/nslocale/1643026-languagecode?language=objc
Added branching to only call APIs when supported
=> Set locale and country code only when supported by Apple OS Version

lib/pal/posix/SystemInformationImpl.cpp, lib/pal/posix/sysinfo_sources.cpp, lib/pal/posix/sysinfo_utils_apple.hpp, lib/pal/posix/sysinfo_utils_ios.mm, lib/pal/posix/sysinfo_utils_mac.mm
https://1dsdocs.azurewebsites.net/schema/PartA/device.html#deviceclass
=> Add device class field for iOS

build-all.bat
Other devs (such as me) want to use UWP static library in their projects. Adding `win10-lib` build into the script will make it easier to build all needed binaries using CI pipeline.
=> add win10-lib (static UWP) build into build-all.bat

lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/HttpClient.java, lib/android_build/maesdk/src/test/java/com/microsoft/applications/events/EventsUnitTest.java, lib/pal/posix/SystemInformationImpl_Android.cpp
https://1dsdocs.azurewebsites.net/schema/PartA/device.html#deviceclass
=> Add device class field for Android

docs/List-of-OSS-Components.md
1DS SDK brings the snapshot of some of the OSS components ( Zlib, sqlite3, Reachability, sha1 ) for historical reasons ( custom patches, ease of build ). These components use functions that often get flagged in different security scans ([here](https://github.com/microsoft/cpp_client_telemetry_modules/issues/161) and [here](https://github.com/microsoft/cpp_client_telemetry_modules/issues/159)). Customers are not enforced to use these components for 1DS SDK build, and can also optionally use their own snapshot of these components for the build. Eg, an android app may be using room-db instead of sqlite3 DB.   This PR adds a disclaimer for customers to use these components in their build only if it meets their security and licensing requirements.
=> Add OSS usage disclaimer

.github/workflows/build-posix-latest.yml, .github/workflows/build-ubuntu-1804.yml, README.md
Trying to bring clarity on build/supported matrix as mentioned in #949
- CI coverage is only supported for ubuntu-18.04 and ubuntu-20.04 as these are the only environment available under Github. We can separately bring ubuntu-14.04 and ubuntu-16.04 under CI coverage by running under container env. 
- 1DS SDK build breaks under ubuntu 14.04 with gcc 4.8.x ( default compiler ) and gcc 4.9.x. It is successful with gcc5.5. `Build Environments` section is updated to reflect that.
- 1DS SDK builds successfully on ubuntu 16.04 ( with gcc 5.5.x ) and ubuntu 18.04 (with gcc 7.5.x ) and this is updated in the `Build Environments` section.
=> Update supported platforms and Build Environments

tests/unittests/InformationProviderImplTests.cpp
Unit test compilation is failing with error
``
/home/runner/work/cpp_client_telemetry/cpp_client_telemetry/tests/unittests/InformationProviderImplTests.cpp:30:9: error: ‘GetCallbacks’ function uses ‘auto’ type specifier without trailing return type
30 |         const auto& GetCallbacks() { return callbacks; }
|         ^~~~~
/home/runner/work/cpp_client_telemetry/cpp_client_telemetry/tests/unittests/InformationProviderImplTests.cpp:30:9: note: deduced return type only available with ‘-std=c++14’ or ‘-std=gnu++14’
make[2]: *** [tests/unittests/CMakeFiles/UnitTests.dir/build.make:398: tests/unittests/CMakeFiles/UnitTests.dir/InformationProviderImplTests.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:219: tests/unittests/CMakeFiles/UnitTests.dir/all] Error 2
``
1DS SDK should compile …
=> Fix unit test compilation in CI

Android.bp
This build file enables Android platform builds to include this telemetry library directly. This is to support using source code releases from this Github repo in Surface Android builds without maintaining a fork just to add a build file.
=> Add Android.bp to support Android platform builds

lib/http/HttpClient_WinInet.cpp
#973 
- "To ensure all data is retrieved, an application must continue to call the InternetReadFile function until the function returns TRUE and the lpdwNumberOfBytesRead parameter equals zero." [InternetReadFile](https://docs.microsoft.com/en-us/windows/win32/api/wininet/nf-wininet-internetreadfile) Updating the while condition to match API documentation
- "The lpdwNumberOfBytesRead parameter will be populated on async completion, so it must exist until INTERNET_STATUS_REQUEST_COMPLETE. The same is true of lpBuffer parameter.." [Async InternetReadFile](https://docs.microsoft.com/en-us/windows/win32/wininet/asynchronous-example-application) Ensuring the byte count & buffer stays valid by making them member variables.
The bug is reproducible with slower network condition. Tested by …
=> Fix HttpClient SendRequestAsync bugs

.github/workflows/test-win-latest.yml, README.md, build-tests.cmd
windows-2016 is deprecated (https://github.com/actions/virtual-environments/issues/4312), the build is failing when running on windows-2019
=> Use msbuild from environment

lib/pal/InformationProviderImpl.cpp
I'm from Outlook iOS team. Not sure if this is a false positive, so please correct me if I'm wrong. The `Thread Sanitizer` complains the potential data race.
=> Try to fix the potential data race in InformatonProviderImpl

Solutions/win32-dll/win32-dll.vcxproj
This is an update to PR #980, which fixes the win32-dll build. In [this comment](https://github.com/microsoft/cpp_client_telemetry/pull/980#pullrequestreview-843123385) @lalitb correctly pointed out that there was an additional win32-lib reference that was now not necessary. It also breaks the build via multiple definitions and therefore must be removed. Thanks for pointing that out! This change will resolve the issue.
Local testing: build-x64Debug.bat script now correctly builds the dll
=> Finish DLL Build Fix

lib/callbacks/DebugSource.cpp
I'm from Outlook Mobile iOS team. While debugging with ThreadSanitizer, found another possible data race.
=> Fix the data race in DispatchEvent

lib/stats/Statistics.cpp, lib/stats/Statistics.hpp
Can we remove the usage of m_intervalMs, or if this is a false alarm for the data race?
=> Try to fix the potential data race in Statistics

.gitmodules
There are vulnerabilities in the nuget packages from `krabsetw` submodule. This change is moving the commit forward to try and fix the issue.
The error we are seeing in our pipeline:
```
Starting Multifeed Nuget Security Analysis: 
third_party/cpp_client_telemetry/third_party/krabsetw/Microsoft.O365.Security.Native.ETW/.nuget/NuGet.Config - Missing <clear/> statement.
third_party/cpp_client_telemetry/third_party/krabsetw/krabs/.nuget/NuGet.Config - Missing <clear/> statement.
Starting Multifeed Python Security Analysis: 
Starting CFS NuGet Analysis: 
third_party/cpp_client_telemetry/third_party/krabsetw/Microsoft.O365.Security.Native.ETW/.nuget/NuGet.Config - External feeds found in the file.
third_party/cpp_client_telemetry/third_party/krabsetw/krabs/.nuget/NuGet.Config - External feeds …
```
=> Update krabsetw commit

lib/http/HttpClient_CAPI.cpp, lib/include/mat/json.hpp
We noticed that in our mirrored branch codeQL raises some errors and after looking into them decided they were false positives:
1. "Dereference of potentially uninitialized pointer field" in HttpClient_CAPI.cpp - the shared_ptr operation is dereferenced within an if block that checks it isn't null, in addition it is default constructed with nullptr so in the case that it isn't null, it means it was purposely assigned a non garbage value. I added the lgtm comment with justification to suppress the error and changed the initialization of operation for better clarity on its initialized value.
link to the error:
2. "Alert Suppression Without Justification" in json.hpp - The function scan_number() uses goto which raised a codeQL error which was later suppressed with the comment "lgtm …
=> Suppress false positive CodeQL errors

CMakeLists.txt
**Issue**
Recently we did the integration of the 1DS library in a common xplat repo and built it for iOS. The common xplat repo contains 1DS as a submodule and adds it as a subdirectory in CMakeList. Post the integration and building it for iOS we observed that the minimum supported OS Version (LC_VERSION_MIN_IPHONEOS) is not getting set in the generated framework. Hence, the build is failing while submitting to test flight.
**RCA**
We observed that 1DS CMakeLists is forcefully setting the CMAKE_OSX_DEPLOYMENT_TARGET as an empty string which is causing the issue (`set(CMAKE_OSX_DEPLOYMENT_TARGET "" CACHE STRING "Force unset of the deployment target for iOS" FORCE)`).
**Solution**
Configuring an option that gives the flexibility on whether the module building 1DS wants this behavior or …
=> Configuring option for force resetting the osx deployment target

wrappers/obj-c/ODWLogConfiguration.mm
**Bug:**
The `ODWLogManager :+(nullable ODWLogger *)loggerWithTenant:(nonnull NSString *)tenantToken source:(nonnull NSString *)source withConfig:(nonnull ODWLogConfiguration *)config 
` always picks the most recent collector URI for all the loggers that have been created using this API.
****Issue Raised with all the details:**** - https://github.com/microsoft/cpp_client_telemetry/issues/991
**Reason:**
`static` configuration object was being used that was being shared between all the loggers created using the above API.
**Fix:** 
Removed the `static` and created an independent configuration instance.
Now the events are going through correct collector URL.
=> Fixed the issue of configuration being shared between multiple loggers

lib/http/HttpClient_Apple.mm, lib/pal/WorkerThread.cpp
https://github.com/microsoft/cpp_client_telemetry_modules/issues/176
Multiple users are reporting high memory usage, especially on M1 Macs. We've made some significant gains in the last few months, but we are still running into users seeing 12+GB of usage. I've been in a thread with one such user who has provided leak traces
The "with aria" traces were collected first, in OneDrive's default configuration. The user enabled malloc_history and let the product run until it reached around 1GB usage, at which point it is my understanding that we crashed (this has to do with malloc tracing and not another bug). After that, I had the user disable Aria, and run the same trace again (the "without aria" trace). No crash this time.
From a comparison of the traces, it is obvious that Aria is …
=> Fix Mac Memory leak issue

lib/include/public/EventProperties.hpp, lib/system/EventProperties.cpp
The method does not modify the vt_prop so it should take a const object
=> Use correct `const` modifier in `EventProperties::unpack`

tools/server/Program.cs
By default, Kestrel webserver doesn't allow to accept sync request. See more details [here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#synchronous-io).
However, when .net 1DS SDK is used with default configuration it sends sync request to 1DS test server and as a result request is processed with error:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
Request starting HTTP/1.1 POST http://localhost:63980/OneCollector/ application/bond-compact-binary 494
info: REQ-1[0]
Connection: keep-alive
Content-Type: application/bond-compact-binary
Content-Encoding: gzip
Host: localhost:63980
User-Agent: OneCollectorSDK server
Content-Length: 494
Client-Version: AST-windows-C#-no-1.1.3.308-no
Upload-Time: 1667921679807
client-time-epoch-millis: …
```
=> Allow Kestrel webserver to use synchronous IO

tools/decoder/Decoder.cs
At the moment test server produces
```
Exception: System.IO.EndOfStreamException: Unexpected end of stream reached.
at Bond.Protocols.Throw.EndOfStreamException()
at Bond.IO.Safe.InputBuffer.EndOfStream(Int32 count)
at Bond.IO.Safe.InputBuffer.ReadUInt8()
at lambda_method(Closure , CompactBinaryReader`1 )
at Bond.Deserializer`1.Deserialize[T](R reader)
at Bond.Deserialize`1.From[R](R reader)
at CommonSchema.Decoder.FromBondToJSONList(Boolean outputCompactJson, Boolean flatExt)
```
Even though [Decoder.cs](https://github.com/microsoft/cpp_client_telemetry/blob/7f36d8933e621f90513f69d78a40529fcc47a088/tools/decoder/Decoder.cs#L33) successfully read data and send successful response.
As I don't know better way to handle / detect that end of stream is reached and it seems that 1DS Test Server …
=> Hide misleading exception

build-all.bat, build-gtest.sh, build-tests.cmd, lib/android_build/gradlew.bat
Fixes: #1081 
The `ubuntu-latest` virtual environment for GitHub is upgraded to `ubuntu-22.04`, which brings `g++-11.0` as default compiler. And the version of googletest using by 1ds-sdk (`v1.11.1`) doesn't build successfully with new compiler. Refer - https://github.com/google/googletest/pull/3797 and https://github.com/google/googletest/issues/3219. The fix is to upgrade the googletest to latest version `v1.12.1`.
=> [Fix: 1081] upgrade googletest to v1.12.1

lib/include/public/VariantType.hpp
Fix: #1078
`char` type is `unsigned char` by default in ARM processor (https://developer.arm.com/documentation/dui0472/k/C-and-C---Implementation-Details/Basic-data-types-in-ARM-C-and-C--), and `signed char` in x86 processor. This causes the comparison `'\x00' <= *c` as always true in ARM, and hence gcc compiler throws the warning "comparison is always true due to limited range" which is treated as error, and fails. Typecasting the char value to signed before comparison fixes the issue. This conversion is safe to do as it will typecast - 
- signed char to signed char in x86 processor
- unsigned char to signed char in ARM processor
and both are type safe conversions.
=> Fix #1078 : Fix ARM build warning on Linux with gcc compiler

tests/unittests/PalTests.cpp
main repo unit-tests are transiently failing in CI for private repo, as the System Time and Steady Time obtained from PAL layer for POSIX system ( MacOS) after sleep is going beyond the maximum value in range specified in unit-test. This is probably because of low configuration VMs sometime allocated for the tests. 
```
[ RUN      ] PalTests.MonotonicTime
/Users/runner/work/cpp_client_telemetry_modules/cpp_client_telemetry/tests/unittests/PalTests.cpp:91: Failure
Value of: t1 - t0
Expected: is < 900
/Users/runner/work/cpp_client_telemetry_modules/cpp_client_telemetry/tests/unittests/PalTests.cpp:73: Failure
Value of: t1
Expected: is < 1668049421220
Actual: 1668049421225 (of type long long)
/Users/runner/work/cpp_client_telemetry_modules/cpp_client_telemetry/tests/unittests/PalTests.cpp:73: …
```
=> Fix unit-test for CI build of private repo.

Solutions/win32-cs/Program.cs, examples/cpp/EventSender/EventSender.cpp, examples/cpp/EventSender/direct.config, lib/android_build/app/src/androidTest/java/com/microsoft/applications/events/maesdktest/LogManagerDDVUnitTest.java, lib/include/public/ILogConfiguration.hpp, lib/shared/LogConfigurationCX.hpp, tests/functests/APITest.cpp, tests/unittests/HttpRequestEncoderTests.cpp
The current default URLs for Collector the SDK is using are not the preferred URLs. We no longer want teams to use EMEA, NOAM or APAC URLs, because those are geographic boundaries and not data boundaries. We also don't want the "self" URL to be used, since that was never intended to be public. That was intended for internal use. 
The preferred URLs are:
mobile.events.data.microsoft.com
eu-mobile.events.data.microsoft.com
us-mobile.events.data.microsoft.com
au-mobile.events.data.microsoft.com
jp-mobile.events.data.microsoft.com
..
All future geo URLs will follow this same pattern.
=> Fixing URLs for Collector

lib/include/public/ILogConfiguration.hpp, lib/offline/ISqlite3Proxy.hpp, lib/offline/OfflineStorageHandler.cpp, lib/offline/OfflineStorage_SQLite.cpp, lib/offline/OfflineStorage_SQLite.hpp, lib/offline/SQLiteWrapper.hpp, wrappers/obj-c/ODWLogConfiguration.h, wrappers/obj-c/ODWLogConfiguration.mm
The way SQLite is initialized (synchronous=NORMAL config) introduces potential issues with durability of changes/updates in some corner cases (power loss, ungraceful process termination/exit, etc).
iOS Outlook logs telemetry in scenarios where if some critical validation/check failed and cannot be handled process will self-terminate. In between logging the event and terminating we call Flush() to avoid lost events. If we checkpoint the DB before returning from the Flush() call app can safely assume no events will be lost. This change introduces an option that enables such behavior.
Alternative solution would be to use the default configuration (with synchronous=FULL) which doesn't have that problem but has overhead of filesystem syncing for each transaction which makes it a bad idea from …
=> Introduce option to checkpoint database on Flush()

.github/workflows/build-ubuntu-2004.yml, README.md
ubunu-18.04 runner images (used in our CI) won't be supported from April 1st 2023 as mentioned here - https://github.com/actions/runner-images/issues/6002.
So changing the relevant CI pipeline to use ubuntu 20.04.
Also adding an entry for ubuntu `20.04 LS in README.md now that the ubuntu-latest refers to ubuntu-22.04 LTS.
One of the errors from pipeline - https://github.com/microsoft/cpp_client_telemetry/actions/runs/4348190703 for using deprecated image. Thanks @sid for pointing out.
=> Use Ubuntu 20.04 runner image for CI

lib/android_build/app/build.gradle, lib/android_build/app/src/main/cpp/native-lib.cpp, lib/android_build/app/src/main/java/com/microsoft/applications/events/maesdktest/MaeUnitLogger.java, lib/android_build/app/src/main/java/com/microsoft/applications/events/maesdktest/MainActivity.java, lib/android_build/app/src/main/res/layout/activity_main.xml, lib/android_build/app/src/main/res/values/colors.xml, lib/android_build/app/src/main/res/values/styles.xml, lib/android_build/build.gradle, lib/android_build/maesdk/build.gradle, lib/android_build/maesdk/src/test/java/com/microsoft/applications/events/HttpClientRequestTest.java
Subset of #1103
~Upgrade room 2.2.6 -> 2.4.3 (latest 2.5.1)~ (requires java upgrade)
Upgrade espresso-core
Clean not needed libraries
Move HttpClientRequestTest to the library project, so it will run during build
=> Android, upgrade room and test deps, cleanup not required

Solutions/before.targets
**Problem Description**
Common targets check for 2015 and 2017, but not for 2022. Prefer v143 toolchain if using vs2022. There is still an option to manually propagate the `PlatformToolset` parameter, so it should not break any of the existing Build pipelines.
=> Update before.targets to support Visual Studio 2022

Solutions/build.compact-signals.props, lib/include/mat/config-compact-signals.h, lib/include/mat/config-default.h
This PR includes two changes:
1. move `#define HAVE_MAT_SIGNALS` to check `__has_include` before using it
2. adds `config-compact-signals` and `build.compact-signals.props`  to be used later in github workflow
=> define signals module if __has_include is available

lib/android_build/gradle.properties, lib/android_build/maesdk/build.gradle
Just like what we've discussed in #1136, passing parameter to build is more explicit.
We can get the CXX_FLAGS from the following:
1. Add CXX_FLAGS in gradle.properties
2. Pass param as -PCXX_FLAGS="xxxx" in command line, for example: `./gradlew :maesdk:assemble -PCXX_FLAGS="HAVE_CS4=1"`
3. Read the CXXFLAGS env variable (This is the fallback option)
=> Pass CXX_FLAGS from properties to maesdk module

wrappers/obj-c/CMakeLists.txt
Same fix as here https://github.com/microsoft/cpp_client_telemetry/pull/1142
=> Add missing frameworks to obj-c sdk

examples/cpp/SampleCpp/CMakeLists.txt
Resolves this issue https://github.com/microsoft/cpp_client_telemetry/issues/1140 by adding missing frameworks
=> Fix linker errors on macOS sample project

tests/unittests/MemoryStorageTests.cpp
Similar to existing warning for clang.
=> Suppress C5258 in MemoryStorageTests.

tests/unittests/StringUtilsTests.cpp
Existing code performed a by-value copy of the std::string into the range declarator. Replace with a const&
=> Fix inefficient range-based for loop identified by static analysis.

lib/utils/StringUtils.cpp
Not exactly sure why this method exists. I'd like to replace the toString methods across the board (except for our own types), but that's probably a downstream change.
=> Replace PAL's to_string with std::to_string.

lib/tpm/TransmissionPolicyManager.cpp
The method doesn't mutate any members and can't throw exceptions.
=> Mark PauseGuard::isPaused as const noexcept.

docs/EUDB-compliance.md, examples/cpp/EventSender/EventSender.cpp, lib/api/IRuntimeConfig.hpp, lib/config/RuntimeConfig_Default.hpp, lib/tpm/TransmissionPolicyManager.cpp
Certain Microsoft applications are in scope to be European Union Data boundary (EUDB) Compliant.
This FAQ for 1DS SDK addresses one of the 8 EUDB requirements:
- Data Residency which requires all EU data accessed, processed, displayed/viewed with certain applications must reside within EU. 1DS Collector itself ensures that the data routed to regional collection end-point is maintained in EU. Products must perform determination whether or not a specific installation / seat within a Commercial / Enterprise setting belongs to EU or not. This determination process is out-of-scope for 1DS SDK itself, and may be performed via another systems/APIs, such as ECS, OneSettings, MSGraph, etc.
The goal of this PR is:
- to provide an example how to configure 1DS C++ SDK to respect a regional URL.
- how …
=> EUDB compliance recommendations and example

lib/include/public/mat.h
Fixing the ordering of EVT_OP_MAX, which got checked in https://github.com/microsoft/cpp_client_telemetry/pull/1198
=> Fix EVT_OP_MAX order 

docker/rockylinux9/Dockerfile
By adding --setopt=tsflags=nodocs to this yum install command, we're instructing yum not to install the documentation files associated with the packages. This help in avoiding the conflict we're facing.
=> Fix Rhel9 conflict due to documentation

build.sh
The correct syntax here is `${VARIABLE:-REPLACEMENT}`. The dash is part of the operator.
Since the replacement also needs to start with a dash, two dashes are required.
For instance:
```bash
CMAKE_OPTS="${CMAKE_OPTS:-DBUILD_SHARED_LIBS=OFF}"
echo $CMAKE_OPTS
```
Will output
```
DBUILD_SHARED_LIBS=OFF
```
And
```bash
CMAKE_OPTS="${CMAKE_OPTS:--DBUILD_SHARED_LIBS=OFF}"
echo $CMAKE_OPTS
```
Will output
```
-DBUILD_SHARED_LIBS=OFF
```
This issue was causing the -DBUILD_SHARED_LIBS=OFF default to be ignored if a user did not set CMAKE_OPTS:
```
2023-09-06T22:39:53.3228622Z cmake -DMAC_ARCH=x86_64 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PACKAGE_TYPE=deb -DCMAKE_CXX_FLAGS="-DHAVE_MAT_EVT_TRACEID=1" DBUILD_SHARED_LIBS=OFF ..
CMake Warning:
Ignoring extra path from command line: …
```
=> Fix a syntax error in build.sh

lib/include/public/Version.hpp, lib/tpm/TransmissionPolicyManager.cpp, lib/tpm/TransmissionPolicyManager.hpp
MacOS is failing due to some code in this PR. Hence reverting this change for time being until we fix exact issue to ensure correct MIP SDK 1DS pipeline
=> Revert fix for upload thread stoppage and max priority

tools/server/run.cmd, tools/server/run.sh, tools/server/server.csproj
In our e2e tests, when we are using 1DS Test Server, pipeline uses .net6 (we have been targeting custom branch with the change `user/iankudinova/update_server_to_net6`).
I want to add the support .net6 to the main branch.
In case at some other project / plcases .net core 3 is used for the Test telemetry server I kept both version.
So Users will have to specify --framework version, when they run server.
Existed scripts: 
- `run.cmd`
- `run.sh`
were updated to support --framework option and use .net core 3 as a default option
=> Add target .net 6 for the 1DS Test Server

.github/CODEOWNERS
This will allow us to update the approvers without changing this file.
=> Update .CODEOWNERS to contain 1ds-c-sdk-approver team.

examples/swift/README.md, examples/swift/SamplePackage/Package.swift, examples/swift/SamplePackage/Sources/SamplePackage/SamplePackage.swift, examples/swift/SamplePackage/Tests/SampleTests/SampleTests.swift
Adding sample unit tests to SamplePackage example for swift wrapper to show case the usage w.r.t unit tests.
Added dependency to the objC moduel for UT target and added required libs and fwks to be linked to the build target.
Testing:
- Swift build and test passing
- Sample test is passing
=> Adding sample unit tests to SamplePackage example for swift wrapper to show case the usage w.r.t unit tests

tests/unittests/MemoryStorageTests.cpp
Fix is to move the complex c'tors into a Test Facet, so that they're initialized and destroyed only when the Test is run.
=> Fix an Apple break in Office around complex c'tors running at binary load time.

tests/functests/LogSessionDataFuncTests.cpp, tests/unittests/LogSessionDataTests.cpp
Two test files were left out without cleanup after mbu test for ariasdk. Adding change to clean them up.
**Fix:**
_**test.ses:**_
reason for this being left out after mbu test is due to TEST method is being used insteasd of TEST_F which is with fixture responsible for calling the setup and tear down functions of the test class.
more info at: [link (Opens in new window or tab)](https://google.github.io/googletest/primer.html#same-data-multiple-tests)
**_sesfile.ses:_**
this is being left out since the cleanup funcitons are not being called after the setup.
=> Cleaning leftover test files after test completion

wrappers/swift/Sources/OneDSSwift/EventProperties.swift
Some of the properties defined in objc odwEventProperties.h file did have corresponding getters and setters in corresponding swift wrapper file.
Adding those in this change.
=> Adding setters and getters for properties in EventProperties.swift for swift wrappers

lib/http/HttpClient_Curl.hpp
```
lib/./http/HttpClient_Curl.hpp: In member function ‘long int Microsoft::Applications::Events::CurlHttpOperation::Send()’:
lib/./http/HttpClient_Curl.hpp:211:39: error: ‘CURLINFO_LASTSOCKET’ is deprecated: since 7.45.0. Use CURLINFO_ACTIVESOCKET [-Werror=deprecated-declarations]
211 |         res = curl_easy_getinfo(curl, CURLINFO_LASTSOCKET, &sockextr);
```
=> Fix deprecated CURL API usage.

lib/offline/SQLiteWrapper.hpp
Variable is only used for debug purposes and causes error on the local build due to being unused.
=> Fixing release build unused variable error by adding conditional complation to the code run only for debug builds

wrappers/swift/Sources/OneDSSwift/ObjCTypes.swift
Objc enums accessed in swift have their names removed from the enum values due to convention. Adding comment about it to let the users know.
=> adding comment about using the typealised enums in swift from objc 

lib/pal/desktop/NetworkDetector.cpp, lib/pal/desktop/NetworkDetector.hpp, tests/functests/MultipleLogManagersTests.cpp
Update a few methods which do not call throwing functions (or throw themselves) to use the `noexcept` annotation.
Also fixed a best-practice for constant initialization in MultipleLogManagersTests RequestHandler type.
=> Add noexcept annotation where applicable

examples/cpp/SampleCppMini/main.cpp
Fixes build break in SampleCppMini by adjusting `ticketNames` array size to match number of elements the array is initialized with.
=> SampleCppMini - adjust ticketNames array size

.github/workflows/codeql-analysis.yml
CodeQL v2 is going to be deprecated. See below link for more details.
https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
=> Upgrade CodeQL from v2 to v3

.github/workflows/codeql-analysis.yml
Switched to Windows for building C#. And the CI of Android also runs on Windows.
=> Add Java to CodeQL scan list

build.sh
Fixes: #1269 
It [seems ](https://github.com/actions/runner-images/issues/9272)that macOS-13 image has `runner:admin` permissions for `/usr/local/`. But macOS-14 has `root:wheel`. So modified `build.sh` so that the build-tools script for Apple is executed as `sudo`, just like for Linux.
=> MacOS CI failure fix

README.md
Update the `Getting Started` section to enable users with a Microsoft alias (including employees and contractors) to reach out to internal community channels and join community meeting invites. The internal links will be eventually updated (as a separate PR) in the private `cpp_client_telemetry_modules` repository.
=> Update "Getting started" section.

lib/api/CorrelationVector.cpp, lib/filter/EventFilterCollection.cpp, lib/include/public/Enums.hpp, lib/include/public/IDataViewer.hpp, tests/unittests/BondSplicerTests.cpp
A few files use types defined in headers that are missing, and this is revealed through build errors when building with gcc. Something about libstdc++ may have refactored header files such that headers that previously were inherited now must be explicitly included.
fixes #1288
=> Fix for build errors when building with gcc 13

lib/include/public/mat.h
-Wcast-function-type-mismatch is a new diagnostic issued by clang 19.  Add an additional cast to silence the diagnostic.  The underlying issue is that `GetProcAddress` unconditionally returns `FARPROC` instead of matching the real function signature.
=> Prevent `-Wcast-function-type-mismatch` diagnostics from clang

tests/functests/MultipleLogManagersTests.cpp
This change fixes Privacy Guard related unit test and functional test failures.
1) one unit test failure that fails 1/3 of the time due to a probabilistic issue.
2) one unit test failure due to test code out of date with production code
3) one functional test failure due to test code out of date with production code.
They were not discovered earlier because some of the test cases are not run in 1DS C++ SDK main repo build pipelines - privacy guard is in submodule repo, so main repo does not compile them along with public SDK files, hence some unit tests are disabled using a macro.
I discussed with Lalit and the agreement we settled is that developers need to run all unit test locally before submitting PR for review. I also modified our developers guide to include this in Privacy Guard …
=> Fix Privacy Guard unit test failures

lib/include/public/Version.hpp, tests/unittests/CMakeLists.txt, tests/unittests/UnitTests.vcxproj, tests/unittests/UnitTests.vcxproj.filters
Privacy Guard has an initiative for point to a unified schema. 
The new schema stores the data in the Privacy Concern Event. This idea has been implemented in https://github.com/microsoft/cpp_client_telemetry_modules/pull/253.
- Implemented Privacy Concern Event
- Integrated NotifyConcern with the new schema 
- Added tests to cover the new changes.
=> update version to point to PG unified schema

tests/functests/CMakeLists.txt
This PR https://github.com/microsoft/cpp_client_telemetry/commit/c480743a8603dd34bb8b054877ced15bc48870c1 added COPY_FILE which is a new command in cmake 3.19 and not present in cmake 3.16.3-1ubuntu1.20.04.1. 
Fixing this by using COPY_FILE only with cmake 3.19+ where it is introduced
=> using COPY_FILE only with cmake 3.21+ where it is introduced

CMakeLists.txt
Hi - I'm working on migrating my team's project to use the arm64 iOS simulator. I spent many hours today trying to track down this same issue in another one of our dependencies, so I thought I should contribute my findings back here.
It looks like for the x86_64 simulator, it will assume you want the simulator build even if you pass -miphoneos-version-min (because an x86 iphone makes no sense), but for the arm64 simulator, you need to specify you want the simulator with -mios-simulator-version-min.
=> Support iOS Simulator on arm64

lib/include/public/Version.hpp, tools/version-node.js
Also fix the version generation script to increment the minor and patch release properly. Somehow it stopped worked with previous commits.
=> Bump version for new release - "3.9.22.1"

lib/decoder/PayloadDecoder.cpp, lib/system/JsonFormatter.cpp
In C++17 left-to-right evaluation order for operands of operator[] is not guaranteed when the argument's copy constructor is run.
Evalutation order isn't not relied upon here, so I'm disabling warning.
=> Suppress C4866 in PayloadDecoder and JsonFormatter's usage of json.hpp

lib/pal/PAL.cpp, lib/pal/PAL.hpp, tests/unittests/PalTests.cpp
CodeQL has flagged one or more instances of violations of type "cpp/path-injection" in the file "third_party/cpp_client_telemetry/lib/pal/PAL.cpp".
Violation File Path: third_party/cpp_client_telemetry/lib/pal/PAL.cpp
Line Numbers: 123
Alert Message: Uncontrolled data used in path expression.
QueryID: cpp/path-injection
Example [fix](https://liquid.microsoft.com/Web/Object/Read/ScanningToolWarnings/Requirements/CodeQL.SM01937#Zguide)
=> Fix CodeQL violations of type 'cpp/path-injection in lib/pal

build.sh
The issue prompting this PR is [#1341](https://github.com/microsoft/cpp_client_telemetry/issues/1341), where a positional argument following a switch will cause the switch to be swallowed and not evaluated.
This PR changes how commands are parsed so that:
* All positional arguments are parsed before any switches, in a loop
* Any number of positional arguments will be evaluated
* If there is a conflict (such as 'release' and 'debug', or 'arm64' and 'x86_64'), the error will be detected and the script will terminate
* All parsing occurs before any work (mainly affects the clean step)
* If any arguments follow the final switch, the error will be detected and the script will terminate
Additionally, there was a conflict between the usage statement and logic, in that the usage statement …
=> More robust parsing and arg validation for build.sh

wrappers/obj-c/ODWLogger_private.h
LLVM's STL in Xcode 16.3 has removed a number of implicit internal header includes, meaning we need to be explicit about what STL headers we include for features like std::atomic. Add the necessary includes.
=> [c++23] Add explicit STL includes

tests/unittests/obj-c/ODWReachabilityTests.mm, tests/unittests/unittests-ios.xcodeproj/project.pbxproj, third_party/Reachability/ODWReachability.h, third_party/Reachability/ODWReachability.m
Reachability uses SCNetworkReachabilityRef library which is deprecated in MacOS 10.14 or higher.
Hence, Use NSURLSession for MacOS 10.14 or higher in cpp_client_telemetry/third_party/Reachability and have backward compatibility with SCNetworkReachabilityRef library for versions lower than MacOS 10.14
=> Reachability: use NSURLSession for MacOS 10.14 or higher

lib/android_build/maesdk/src/main/cpp/CMakeLists.txt, lib/jni/SanitizerHelper.hpp, lib/jni/Sanitizer_jni.cpp
add path to modules for android build
fix config
fix spDataInspector renamed to spSanitizer
=> fix sanitizer android

lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/ILogManager.java, lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/LogManager.java, lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/LogManagerProvider.java, lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/Sanitizer.java, lib/jni/LogManager_jni.cpp, lib/jni/Sanitizer_jni.cpp
Add JNI support for san
fix san jni with improper use of c_str
Added  san support to logmanager
=> add san to log manager

lib/CMakeLists.txt
Since `PayloadDecoder.hpp` is a public interface, if people try to use it they will face a linker error because that symbol is not compiled in the library so therefore not included in final binary.
So this PR adds it to CMakeList.txt to ensure payload decoder is compiled and included in the final library binary and we are able to compile and link successfully.
Fixes #1381
=> Including payload decoder into CMakeList.txt for the library
